brain_strategist_kernel:
    resource: "@BrainStrategistKernelBundle/Controller/"
    type:     annotation
    prefix:   /

brain_strategist_calendar:
    resource: "@BrainStrategistCalendarBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect    

hwi_oauth_login:
  resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
  prefix: /login

facebook_login:
    path: /login/check-facebook