brain_strategist_kernel:
    resource: "@BrainStrategistKernelBundle/Controller/"
    type:     annotation
    prefix:   /

brain_strategist_calendar:
    resource: "@BrainStrategistCalendarBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"