    # Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html

services:
    my.oauth_aware.user_provider.service:
        class: HWI\Bundle\OAuthBundle\Security\Core\User\FOSUBUserProvider
        arguments:
            userManager: "@fos_user.user_manager"
            properties: ["pass properties as array"]
    brain_strategist.menu_builder:
        class: BrainStrategist\KernelBundle\Menu\builder
        arguments: ["@knp_menu.factory"]

    brain_strategist.menu_user:
        class: Knp\Menu\MenuItem
        factory_service: brain_strategist_kernel.builder
        arguments: ["@request_stack"]
        tags:
            - { name: knp_menu.menu, alias: userMenu }
    brain_strategist.form.registration:
        class: BrainStrategist\KernelBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }
    brain_strategist.file.twig.extension:
        class: BrainStrategist\KernelBundle\Twig\TwigExtension
        tags:
            - { name: twig.extension }
    brain_strategist.project.twig.extension:
        class: BrainStrategist\ProjectBundle\Twig\TwigExtension
        arguments:
            em: "@doctrine.orm.entity_manager"
            context: "@security.token_storage"
        tags:
            - { name: twig.extension }
    brain_strategist.listener.preexecute:
        class: BrainStrategist\KernelBundle\Predispatcher
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }