services:
#    brain_strategist_kernel.example:
#        class: BrainStrategist\KernelBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]

    brain_strategist.kernel_bundle.oauth.user_provider:
        class: BrainStrategist\KernelBundle\OAuth\UserProvider
        arguments: ["@fos_user.user_manager", {facebook: facebook_id, google: google_id}]

