<?php

namespace BrainStrategist\ProjectBundle\Repository;

/**
 * SeverityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeverityRepository extends \Doctrine\ORM\EntityRepository
{

    public function findAllByProjectId($id)
    {
        $qb = $this->createQueryBuilder('s');
        $qb->where('s.project = :project_id')->setParameter('project_id', $id);
        return $qb;
    }
}
