<?php

namespace BrainStrategist\ProjectBundle\Repository;

/**
 * TicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketRepository extends \Doctrine\ORM\EntityRepository
{

    public function findAllTicketByProjectIdQuery($params)
    {
        extract($params);

        if (!is_null($projectID)) {
            $q = $this->createQueryBuilder('t')
                ->leftJoin('t.projet', 'tp')
                ->leftJoin('t.creator', 'tc')
                ->leftJoin('t.assigned_users', 'tau')
                ->leftJoin('t.category', 'tca')
                ->leftJoin('t.priority', 'tpr')
                ->leftJoin('t.severity', 'ts')
                ->addSelect('tp')
                ->addSelect('tau')
                ->addSelect('tca')
                ->addSelect('tpr')
                ->addSelect('ts')
                ->addSelect('tc')
                ->andWhere('tp.id = :projet_id')
                ->setParameter('projet_id',$projectID);

            $query = $q->getQuery();
            return $query->setHydrationMode(\Doctrine\ORM\Query::HYDRATE_ARRAY);

        }else{
            return false;
        }

}
    public function findAllTicketByProjectId($params=array('limit'=>100,'offset'=>0))
    {
        extract($params);

        if (!is_null($projectID)) {
        $query = $this->findAllTicketByProjectId($params);
         return $query->getArrayResult();

        }else{
            return false;
        }

    }
    public function findAllTicketByUserQuery($params)
    {
        extract($params);

        if (!is_null($userID)) {
            $q = $this->createQueryBuilder('t')
                ->leftJoin('t.projet', 'tp')
                ->leftJoin('t.creator', 'tc')
                ->leftJoin('t.assigned_users', 'tau')
                ->leftJoin('t.priority', 'tpr')
                ->leftJoin('t.category', 'tca')
                ->leftJoin('t.severity', 'ts')
                ->addSelect('tp')
                ->addSelect('tau')
                ->addSelect('tca')
                ->addSelect('tpr')
                ->addSelect('ts')
                ->addSelect('tc')
                ->andWhere('tau.id = :user_id')
                ->setParameter('user_id',$userID);

            $query = $q->getQuery();
            return $query->setHydrationMode(\Doctrine\ORM\Query::HYDRATE_ARRAY);

        }else{
            return false;
        }

    }

    public function findAllTicketByUser($params)
    {
        extract($params);

        if (!is_null($userID)) {
            $this->findAllTicketByUserQuery($params);
            return $query->getArrayResult();

        }else{
            return false;
        }

    }
    public function findOneById($id)
    {
        if (!is_null($id)) {
            $q = $this->createQueryBuilder('t')
                ->leftJoin('t.projet', 'tp')
                ->leftJoin('t.creator', 'tc')
                ->leftJoin('t.assigned_users', 'tau')
                ->leftJoin('t.category', 'tca')
                ->leftJoin('t.severity', 'ts')
                ->leftJoin('t.priority', 'tpr')
                ->leftJoin('t.pictures', 'tpic')
                ->leftJoin('t.status', 'tst')
                ->leftJoin('t.comments', 'tco')
                ->leftJoin('tco.user_comment', 'tco_usr')
                ->leftJoin('tco.pictures', 'tco_pict')
                ->leftJoin('t.logs', 'tl')
                ->addSelect('tp')
                ->addSelect('tco_usr')
                ->addSelect('tau')
                ->addSelect('tco')
                ->addSelect('tpr')
                ->addSelect('tco_pict')
                ->addSelect('tpic')
                ->addSelect('tca')
                ->addSelect('tl')
                ->addSelect('ts')
                ->addSelect('tst')
                ->addSelect('tc')
                ->andWhere('t.id = :ticket_id')
                ->setParameter('ticket_id',$id);

            $query = $q->getQuery();
            return $query->getOneOrNullResult(\Doctrine\ORM\Query::HYDRATE_ARRAY);

        }else{
            return false;
        }

    }
}
