<?php

namespace BrainStrategist\ProjectBundle\Repository;

/**
 * Ticket_CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Ticket_CommentRepository extends \Doctrine\ORM\EntityRepository
{
}
