<?php

namespace BrainStrategist\ProjectBundle\Repository;

/**
 * Ticket_CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Ticket_CategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
