<?php

namespace BrainStrategist\ProjectBundle\Repository;

/**
 * Ticket_LogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Ticket_PriorityRepository extends \Doctrine\ORM\EntityRepository
{

    public function findAllByProjectId($id)
    {
        $qb = $this->createQueryBuilder('tp');
        $qb->where('tp.project = :project_id')->setParameter('project_id', $id);
        return $qb;
    }
}
