<?php

namespace BrainStrategist\KernelBundle\Repository;

/**
 * OrganizationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrganizationRepository extends \Doctrine\ORM\EntityRepository
{
    public function findMyOrganizations($params=array('limit'=>100,'offset'=>0))
    {
        extract($params);

        if (!is_null($userID)) {

            $q = $this->createQueryBuilder('o')
                ->leftJoin('o.usersOrganization', 'uo')
                ->addSelect('uo')
                ->where('o.isActive = 1')
                ->andWhere('uo.id = :user')
                ->setParameter('user',$userID)
                ->setMaxResults($limit)
                ->setFirstResult($offset);


            $query = $q->getQuery();
            return $query->getArrayResult();
        }
        return false;
    }
}
